title:              Blog
tagline:            helping to think 
description:        a place to put things that i'm learning
url:                https://couldbethis.github.io/

author:
  name:             Could B This
  url:              https://github.com/CouldBeThis
  email:            YourName@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
